// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/login.proto

package go_micro_srv_login

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Userdata struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Userdata) Reset()         { *m = Userdata{} }
func (m *Userdata) String() string { return proto.CompactTextString(m) }
func (*Userdata) ProtoMessage()    {}
func (*Userdata) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26af552c9148a54, []int{0}
}

func (m *Userdata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Userdata.Unmarshal(m, b)
}
func (m *Userdata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Userdata.Marshal(b, m, deterministic)
}
func (m *Userdata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Userdata.Merge(m, src)
}
func (m *Userdata) XXX_Size() int {
	return xxx_messageInfo_Userdata.Size(m)
}
func (m *Userdata) XXX_DiscardUnknown() {
	xxx_messageInfo_Userdata.DiscardUnknown(m)
}

var xxx_messageInfo_Userdata proto.InternalMessageInfo

func (m *Userdata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Userdata) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	Login                bool     `protobuf:"varint,1,opt,name=login,proto3" json:"login,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26af552c9148a54, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetLogin() bool {
	if m != nil {
		return m.Login
	}
	return false
}

func (m *Response) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Userdata)(nil), "go.micro.srv.login.Userdata")
	proto.RegisterType((*Response)(nil), "go.micro.srv.login.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for LoginService service

type LoginServiceClient interface {
	LoginOrSignup(ctx context.Context, in *Userdata, opts ...client.CallOption) (*Response, error)
}

type loginServiceClient struct {
	c           client.Client
	serviceName string
}

func NewLoginServiceClient(serviceName string, c client.Client) LoginServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.login"
	}
	return &loginServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *loginServiceClient) LoginOrSignup(ctx context.Context, in *Userdata, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "LoginService.LoginOrSignup", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LoginService service

type LoginServiceHandler interface {
	LoginOrSignup(context.Context, *Userdata, *Response) error
}

func RegisterLoginServiceHandler(s server.Server, hdlr LoginServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&LoginService{hdlr}, opts...))
}

type LoginService struct {
	LoginServiceHandler
}

func (h *LoginService) LoginOrSignup(ctx context.Context, in *Userdata, out *Response) error {
	return h.LoginServiceHandler.LoginOrSignup(ctx, in, out)
}

func init() { proto.RegisterFile("proto/login.proto", fileDescriptor_b26af552c9148a54) }

var fileDescriptor_b26af552c9148a54 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xc9, 0x4f, 0xcf, 0xcc, 0xd3, 0x03, 0xb3, 0x85, 0x84, 0xd2, 0xf3, 0xf5, 0x72,
	0x33, 0x93, 0x8b, 0xf2, 0xf5, 0x8a, 0x8b, 0xca, 0xf4, 0xc0, 0x32, 0x4a, 0x56, 0x5c, 0x1c, 0xa1,
	0xc5, 0xa9, 0x45, 0x29, 0x89, 0x25, 0x89, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x14, 0x17, 0x47, 0x41, 0x62, 0x71, 0x71,
	0x79, 0x7e, 0x51, 0x8a, 0x04, 0x13, 0x58, 0x1c, 0xce, 0x57, 0x8a, 0xe2, 0xe2, 0x08, 0x4a, 0x2d,
	0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe1, 0x62, 0x05, 0x1b, 0x08, 0xd6, 0xcc, 0x11, 0x04,
	0xe1, 0x80, 0x44, 0x4b, 0xf2, 0xb3, 0x53, 0xf3, 0xa0, 0x5a, 0x21, 0x1c, 0x21, 0x3e, 0x2e, 0xa6,
	0xcc, 0x14, 0x09, 0x66, 0xb0, 0x10, 0x53, 0x66, 0x0a, 0xdc, 0x5e, 0x16, 0x84, 0xbd, 0x46, 0xb1,
	0x5c, 0x3c, 0x3e, 0x20, 0x23, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x7c, 0xb9, 0x78,
	0xc1, 0x7c, 0xff, 0xa2, 0xe0, 0xcc, 0xf4, 0xbc, 0xd2, 0x02, 0x21, 0x19, 0x3d, 0x4c, 0xdf, 0xe8,
	0xc1, 0xbc, 0x22, 0x85, 0x55, 0x16, 0xe6, 0x58, 0x25, 0x86, 0x24, 0x36, 0x70, 0x88, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x8f, 0x30, 0xb1, 0x26, 0x01, 0x00, 0x00,
}
